### PR TITLE
Add ruby 2.2.2

### PR DESCRIPTION
**Pull request by stevenschobert**
Thanks for open-sourcing asdf! I'm really enjoying it so far!

I added ruby 2.2.2 to the `list-all` script, but are there any other steps I should take to make sure this works?

### CODE REVIEW

**Comment by HashNuke** [comment]
@stevenschobert Thank you ~!
This is sufficient. The `list-all` script is basically a dummy for people's reference to  :)
You can install ruby versions almost immediately when they are released.

**Comment by stevenschobert** [comment]
Ahhh that makes more sense! I'm a dummy, while switching over from `rbenv` I just assumed the listing was used for more than a guide!

I definitely like it better as a guide :)

**Comment by HashNuke** [comment]
@stevenschobert former rbenv user here too :) Glad you like asdf.
I've been happily using asdf on 2 computers and a server for over a month now. Wrote it for fun & shared it with a friend long back with this message https://github.com/HashNuke/asdf/blob/master/ballad-of-asdf.md. Then restarted & completed the project recently when I was setting up a new computer.

There's some polish required in the main asdf repo (like better error messages when a version isn't available, etc). I hope to iron out those someday.

**Comment by stevenschobert** [comment]
hah! Thats awesome, love the ballad! Yeah I originally came across asdf through this article, while looking for a version manager for elixir:
https://archives.kevin.disneur.me/2015-06-14-elixir-on-circleci.html

Since then I've also been able to drop `rbenv` and `nvm`, which has been great.

Happy to help contribute down the road if you ever need it! :+1:

**Comment by HashNuke** [comment]
@stevenschobert Thank you ~!

I forgot to inform Kevin about a new feature I added recently. If there's a `.tool-versions` file in current dir, you can just run "asdf install" and it'll install all specified in the file. Don't have to install each one manually.

**Pull request merged**
